plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rood.fastbuy'
    compileSdk 35

    defaultConfig {
        applicationId 'com.rood.fastassist.v3'
        minSdk 26
        targetSdk 35
        versionCode 30
        versionName '3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
